export enum Factions {
    Illuminati = "Illuminati",
    Daedalus = "Daedalus",
    TheCovenant = "The Covenant",
    ECorp = "ECorp",
    MegaCorp = "MegaCorp",
    BachmanAndAssociates = "Bachman & Associates",
    BladeIndustries = "Blade Industries",
    NWO = "NWO",
    ClarkeIncorporated = "Clarke Incorporated",
    OmniTekIncorporated = "OmniTek Incorporated",
    FourSigma = "Four Sigma",
    KuaiGongInternational = "KuaiGong International",
    FulcrumSecretTechnologies = "Fulcrum Secret Technologies",
    BitRunners = "BitRunners",
    TheBlackHand = "The Black Hand",
    NiteSec = "NiteSec",
    Aevum = "Aevum",
    Chongqing = "Chongqing",
    Ishima = "Ishima",
    NewTokyo = "New Tokyo",
    Sector12 = "Sector-12",
    Volhaven = "Volhaven",
    SpeakersForTheDead = "Speakers for the Dead",
    TheDarkArmy = "The Dark Army",
    TheSyndicate = "The Syndicate",
    Silhouette = "Silhouette",
    Tetrads = "Tetrads",
    SlumSnakes = "Slum Snakes",
    Netburners = "Netburners",
    TianDiHui = "Tian Di Hui",
    CyberSec = "CyberSec",
    Bladeburners = "Bladeburners",
    ChurchOfTheMachineGod = "Church of the Machine God",
    ShadowsOfAnarchy = "Shadows of Anarchy",
}

export const FactionsList = [
    Factions.Illuminati,
    Factions.Daedalus,
    Factions.TheCovenant,
    Factions.ECorp,
    Factions.MegaCorp,
    Factions.BachmanAndAssociates,
    Factions.BladeIndustries,
    Factions.NWO,
    Factions.ClarkeIncorporated,
    Factions.OmniTekIncorporated,
    Factions.FourSigma,
    Factions.KuaiGongInternational,
    Factions.FulcrumSecretTechnologies,
    Factions.BitRunners,
    Factions.TheBlackHand,
    Factions.NiteSec,
    Factions.Aevum,
    Factions.Chongqing,
    Factions.Ishima,
    Factions.NewTokyo,
    Factions.Sector12,
    Factions.Volhaven,
    Factions.SpeakersForTheDead,
    Factions.TheDarkArmy,
    Factions.TheSyndicate,
    Factions.Silhouette,
    Factions.Tetrads,
    Factions.SlumSnakes,
    Factions.Netburners,
    Factions.TianDiHui,
    Factions.CyberSec,
    Factions.Bladeburners,
    Factions.ChurchOfTheMachineGod,
    Factions.ShadowsOfAnarchy,
];

export const RegularFactions = [
    Factions.Illuminati,
    Factions.Daedalus,
    Factions.TheCovenant,
    Factions.ECorp,
    Factions.MegaCorp,
    Factions.BachmanAndAssociates,
    Factions.BladeIndustries,
    Factions.NWO,
    Factions.ClarkeIncorporated,
    Factions.OmniTekIncorporated,
    Factions.FourSigma,
    Factions.KuaiGongInternational,
    Factions.FulcrumSecretTechnologies,
    Factions.BitRunners,
    Factions.TheBlackHand,
    Factions.NiteSec,
    Factions.Aevum,
    Factions.Chongqing,
    Factions.Ishima,
    Factions.NewTokyo,
    Factions.Sector12,
    Factions.Volhaven,
    Factions.SpeakersForTheDead,
    Factions.TheDarkArmy,
    Factions.TheSyndicate,
    Factions.Silhouette,
    Factions.Tetrads,
    Factions.SlumSnakes,
    Factions.Netburners,
    Factions.TianDiHui,
    Factions.CyberSec,
];

export const FactionsToJoin = [
    Factions.Illuminati,
    Factions.Daedalus,
    Factions.TheCovenant,
    Factions.ECorp,
    Factions.MegaCorp,
    Factions.BachmanAndAssociates,
    Factions.BladeIndustries,
    Factions.NWO,
    Factions.ClarkeIncorporated,
    Factions.OmniTekIncorporated,
    Factions.FourSigma,
    Factions.KuaiGongInternational,
    Factions.FulcrumSecretTechnologies,
    Factions.BitRunners,
    Factions.TheBlackHand,
    Factions.NiteSec,
    Factions.SpeakersForTheDead,
    Factions.TheDarkArmy,
    Factions.TheSyndicate,
    Factions.Silhouette,
    Factions.Tetrads,
    Factions.SlumSnakes,
    Factions.Netburners,
    Factions.TianDiHui,
    Factions.CyberSec,
    Factions.Bladeburners,
    Factions.ChurchOfTheMachineGod,
    Factions.ShadowsOfAnarchy,
];